import type { Report } from './types';

export const mockReports: Report[] = [
  {
    id: '1',
    title: 'Broken water pipe',
    description: 'Main water pipe in the central square has been leaking for 3 days.',
    type: 'Water',
    severity: 'High',
    status: 'Pending',
    location: { lat: 19.043, lng: 72.859 },
    zone: 'Dharavi-Mumbai',
    user: { id: 'u1', name: 'Ravi Sharma', avatarUrl: 'https://placehold.co/100x100' },
    imageUrl: 'https://placehold.co/600x400',
    createdAt: '2023-10-29T10:00:00Z',
  },
  {
    id: '2',
    title: 'No electricity in block C',
    description: 'Power has been out for over 24 hours in the entire C block area.',
    type: 'Electricity',
    severity: 'High',
    status: 'In Progress',
    location: { lat: 19.041, lng: 72.861 },
    zone: 'Dharavi-Mumbai',
    user: { id: 'u2', name: 'Priya Singh', avatarUrl: 'https://placehold.co/100x100' },
    createdAt: '2023-10-28T14:30:00Z',
  },
  {
    id: '3',
    title: 'School roof damaged',
    description: 'The roof of the primary school is damaged and leaks during rain.',
    type: 'Education',
    severity: 'Medium',
    status: 'Pending',
    location: { lat: 19.045, lng: 72.857 },
    zone: 'Dharavi-Mumbai',
    user: { id: 'u3', name: 'Amit Patel', avatarUrl: 'https://placehold.co/100x100' },
    imageUrl: 'https://placehold.co/600x400',
    createdAt: '2023-10-27T09:00:00Z',
  },
  {
    id: '4',
    title: 'Clogged public toilets',
    description: 'The community toilets near the market are blocked and unusable.',
    type: 'Sanitation',
    severity: 'High',
    status: 'Resolved',
    location: { lat: 18.5204, lng: 73.8567 },
    zone: 'Pune Slums',
    user: { id: 'u1', name: 'Ravi Sharma', avatarUrl: 'https://placehold.co/100x100' },
    createdAt: '2023-10-26T18:00:00Z',
  },
  {
    id: '5',
    title: 'Need for a local clinic',
    description: 'The nearest clinic is 5km away, a local health post is urgently needed.',
    type: 'Healthcare',
    severity: 'Medium',
    status: 'Pending',
    location: { lat: 18.523, lng: 73.854 },
    zone: 'Pune Slums',
    user: { id: 'u4', name: 'Sunita Gupta', avatarUrl: 'https://placehold.co/100x100' },
    createdAt: '2023-10-25T11:45:00Z',
  },
   {
    id: '6',
    title: 'Inconsistent water supply',
    description: 'Water is only available for 2 hours a day, causing major issues for families.',
    type: 'Water',
    severity: 'Medium',
    status: 'In Progress',
    location: { lat: 19.039, lng: 72.858 },
    zone: 'Dharavi-Mumbai',
    user: { id: 'u2', name: 'Priya Singh', avatarUrl: 'https://placehold.co/100x100' },
    createdAt: '2023-10-24T16:20:00Z',
  },
  {
    id: '7',
    title: 'Streetlights not working',
    description: 'Most streetlights on the main path are out, making it unsafe at night.',
    type: 'Electricity',
    severity: 'Medium',
    status: 'Resolved',
    location: { lat: 18.519, lng: 73.858 },
    zone: 'Pune Slums',
    user: { id: 'u4', name: 'Sunita Gupta', avatarUrl: 'https://placehold.co/100x100' },
    imageUrl: 'https://placehold.co/600x400',
    createdAt: '2023-10-22T20:00:00Z',
  },
];
